# File location: .streamlit/secrets.toml

# Paste the key you got from Google AI Studio here
GEMINI_API_KEY = "AIzaSyDOHFAefKDxT2Uvo6z5zv5krgb43UK6Q-s"

# This just tells the app where to find your other key file
VISION_CREDENTIALS_PATH = "vision_credentials.json"


REPLICATE_API_TOKEN = "r8_PN331IR9zM2zUk8k9d1hzbdS9rgB3t706L3ns"
